Refactor code: create a subclass PlanActionEnv
AdaCore/e3-core pull request #426
Opened 2020-09-18 13:45 UTC by enzbang

Instead of using directly BaseEnv to contain the action environment
(including the name of the action, the qualifier, ...), create a
new subclass PlanActionEnv. This hopefully make the code clearer.

Also change e3.env.BaseEnv type annotations to make it possible to
subclass BaseEnv and keep mypy happy.

add_action_action env parameter is renamed action_env to make it clear
that we're not manipulating BaseEnv objects but PlanActionEnv objects.

TN: T107-002

2020-09-23 07:21 UTC, Nikokrock requested changes
Almost ok minus the fact that some BaseEnv are still passed

2020-09-23 07:21 UTC, Nikokrock commented on src/e3/electrolyt/plan.py
> +        server: Optional[PlanActionEnv] = None,
can be BaseEnv here

2020-09-28 21:43 UTC, brobecke reviewed
Thanks for doing that, Olivier. This makes things clearer for me. I'll let @Nikokrock give the final approval.

2020-09-29 15:58 UTC, Nikokrock approved these changes

2020-10-06 06:16 UTC, merged