Add a new anod dependency kind: download
AdaCore/e3-core pull request #477
Opened 2021-04-16 13:22 UTC by enzbang

When adding a Dependency with require="download" the plan scheduler
forces an installation of the dependency from the downloaded binary
package. If another anod spec has a require="build_tree" dependency
on the same spec then plan scheduler will raise an error.

2021-04-19 07:59 UTC, kokkonisd submitted a review, later dismissed

2021-04-19 08:57 UTC, liaiss approved these changes
Ok for me

2021-04-20 06:29 UTC, Nikokrock requested changes
Can you add a test where you force download with a spec without explicit download primitive.

2021-04-20 06:47 UTC, Nikokrock approved these changes

2021-04-20 07:02 UTC, merged