Set endianness information on aarch64-linux platforms
AdaCore/e3-core pull request #587
Opened 2023-04-15 00:15 UTC by brobecke

The following program shows that the endianness is not set when the platform is aarch64-linux:

    | from e3.env import Env
    | Env().set_target("aarch64-linux")
    | print(Env().target.cpu.endian)

Currently, the program currently prints:

    unknown

This fix allows the endianness to be set to the correct value, which is "little".

This change was tested by running this repository's testsuite as well as AdaCore internal e3-adacore testsuite.

2023-04-17 07:50 UTC, Nikokrock reviewed
This is strange that you need that. aarch64 at the beginning of the file is marked as little-endian

2023-04-17 07:53 UTC, Nikokrock commented
@brobecke the issue is not there but in our our private platform db

2023-04-17 12:40 UTC, brobecke commented
> @brobecke the issue is not there but in our our private platform db

I think we have some big-endian baremetal runtimes. So for aarch64-elf, it would be unknown.

2023-04-17 15:26 UTC, brobecke commented
> I think we have some big-endian baremetal runtimes. So for aarch64-elf, it would be unknown.

FTAOD, what I mean is that I don't think we should assume the endianness is always the same, and thus only rely on it being set at the CPU level. Instead, I think we should set it for each OS, and for platforms where it's undecided, leave it to "unknown".

WDYT?

2023-04-20 14:17 UTC, Nikokrock requested changes
endianness is already set in e3-core for the CPU and nowadays all arm are little endian in practice

2023-04-20 16:37 UTC, closed without merging