Skip the rlimit_ctrl_c and rlimit_forground tests if you're not using tox
AdaCore/e3-core pull request #603
Opened 2023-06-30 14:23 UTC by leocardao

These tests need ptyprocess to run, so they always fail in a production environment.

2023-06-30 14:30 UTC, enzbang requested changes
you should use pytest.mark.skipif as done to skip the test on windows

2023-07-24 14:52 UTC, leocardao commented
@enzbang This is already done.

2023-11-15 07:41 UTC, enzbang commented
@leocardao you have not done what I suggested: using pytest.mark.skipif instead of having an early return in the function code. Currently your patch makes the function pass even if there is a bug. Returning SKIP is much clearer.

2024-01-08 09:38 UTC, closed without merging

2024-01-08 09:38 UTC, leocardao commented
This pull request is obsolete, as ptyprocess is now referenced in setup.py.